try {
    hello();
} catch (error) {
    console.log(error);
}

try {
    another();
} catch  {
    console.log('esto es un error');
}